version: 2

sources:
  - name: samples_data
    database: "{{ target.database }}" ## Variabilize - DONE :)
    schema: STAGING
    tables:
      - name: STG_LOCATION_RAW
      - name: STG_PRODUCT_RAW
      - name: STG_SALES_RAW